### ISSUE TITLE
Client-side tests does not work anymore

### ISSUE THREAD

**Issue by claustres** [kalisio/aktnmap#67]
Things that seems to be broken:
* events management initially related to sideNavToggle selector being not found
* groups management initially related to sideNavToggle selector being not found
* members management initially related to sideNavToggle selector being not found
* deleting account in organisation tests makes testcafé hangs with the following error `TypeError: this.moment.duration(...).format is not a function` (related to https://github.com/DevExpress/testcafe/issues/1750 ?)

Here is a complete log:
```
> aktnmap@0.7.0 cafe D:\Development\kalisio\aktnmap
> testcafe firefox test/*.test.js -S -s screenshots

 Running tests in:
 - Firefox 66.0.0 / Windows 10.0.0

 Account
 - Registration
 × Edit profile (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-2)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-2\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         38 |  }
         39 |  async openSideNav (test) {
         40 |    let isSideNavVisible = await this.isSideNavVisible()
         41 |    if (!isSideNavVisible) {
         42 |      await test
       > 43 |        .click(this.sideNavToggle) // Ensure menu is open
         44 |        .wait(1000)
         45 |    }
         46 |  }
         47 |  async clickIdentity (test) {
         48 |    await this.openSideNav(test)

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:43:10)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 - Edit password
 - Edit email
 - Delete account

 Authentication
(node:18072) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): #<CantObtainInfoForElementSpecifiedBySelectorError>
(node:18072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 √ Invalid login
 √ Registration
 √ Local login
 × Cleanup local user (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-9)

   1) - Error in fixture.afterEach hook -
      AssertionError: expected 'Forbidden: You are not allowed to access service 5cb1d7101275d96bfcb65722/events' to be falsy

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-9\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         43 |export const getUrl = (path) => path ? baseUrl + '/#/' + path : baseUrl
         44 |export const goBack = ClientFunction(() => window.history.back())
         45 |// Access console errors
         46 |export const checkNoClientError = async (test) => {
         47 |  const { error } = await test.getBrowserConsoleMessages()
       > 48 |  await test.expect(error[0]).notOk()
         49 |}
         50 |export const checkClientError = async (test) => {
         51 |  const { error } = await test.getBrowserConsoleMessages()
         52 |  await test.expect(error[0]).ok()
         53 |}

         at Object.<anonymous> (D:\Development\kalisio\aktnmap\test\page-models\index.js:48:31)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 - Google login
 - Cleanup Google user
 - GitHub login
 - Cleanup GitHub user

 Basic
 - Login as default user

 Billing
 √ Registration
 √ Check billing state for unverified user
 √ Check billing state for verified user
 √ Add payment information
 √ Change plan to silver
 √ Add payment card
 √ Change plan to gold
 √ Remove payment card
 √ Change plan to bronze
 √ Delete default organisation
 √ Delete account

 EventTemplates
 √ Users registration
 √ Create template
 √ Copy template
 √ Update template description
 √ Delete template
 √ Clean registrated users

 Events
 × Setup context (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-32)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-32\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         38 |  }
         39 |  async openSideNav (test) {
         40 |    let isSideNavVisible = await this.isSideNavVisible()
         41 |    if (!isSideNavVisible) {
         42 |      await test
       > 43 |        .click(this.sideNavToggle) // Ensure menu is open
         44 |        .wait(1000)
         45 |    }
         46 |  }
         47 |  async clickIdentity (test) {
         48 |    await this.openSideNav(test)

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:43:10)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 × Create events (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-33)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-33\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         85 |      .click(this.fab.find(entry))
         86 |      .wait(1000)
         87 |  }
         88 |  async clickFab (test, entry) {
         89 |    await test
       > 90 |      .click(Selector(entry))
         91 |      .wait(1000)
         92 |  }
         93 |  async isErrorVisible () {
         94 |    await this.error.visible
         95 |  }

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:90:8)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (D:\Development\kalisio\aktnmap\node_modules\core-js\library\modules\_export.js:36:28)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
         at Events.clickFab (D:\Development\kalisio\aktnmap\test\page-models\layout.js:88:32)
         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\events.js:21:16)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (D:\Development\kalisio\aktnmap\node_modules\core-js\library\modules\_export.js:36:28)


 × Delete event (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-34)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-34\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         29 |      .wait(5000)
         30 |  }
         31 |  async deleteEvent (test, eventName) {
         32 |    let eventId = await this.getItemId(test, this.eventsGrid, eventName)
         33 |    await test
       > 34 |      .click(this.idSelector(eventId).find('#card-overflow-menu-entry'))
         35 |      .click(Selector('.q-popover').find('#remove-event'))
         36 |      .click(Selector('.modal-buttons button').nth(0))
         37 |      .wait(5000)
         38 |  }
         39 |  async checkEventsCount (test, count) {

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\events.js:34:8)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 × Clear context (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-35)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-35\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         35 |      .wait(5000)
         36 |  }
         37 |  async deleteGroup (test, groupName) {
         38 |    let groupId = await this.getItemId(test, this.groupsGrid, groupName)
         39 |    await test
       > 40 |      .click(this.idSelector(groupId).find('#card-overflow-menu-entry'))
         41 |      .wait(500)
         42 |    await test
         43 |      .click(Selector('.q-popover').find('#remove-group'))
         44 |      .click(Selector('.modal-buttons button').nth(0))
         45 |      .wait(5000)

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\groups.js:40:8)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 Groups
 × Setup context (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-36)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-36\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         38 |  }
         39 |  async openSideNav (test) {
         40 |    let isSideNavVisible = await this.isSideNavVisible()
         41 |    if (!isSideNavVisible) {
         42 |      await test
       > 43 |        .click(this.sideNavToggle) // Ensure menu is open
         44 |        .wait(1000)
         45 |    }
         46 |  }
         47 |  async clickIdentity (test) {
         48 |    await this.openSideNav(test)

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:43:10)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 √ Create groups
 √ Edit group
 × Add members to groups (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-39)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-39\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         61 |      .wait(5000)
         62 |  }
         63 |  async joinGroup (test, memberName, groupName, role) {
         64 |    let cardId = await this.getItemId(test, this.membersGrid, memberName)
         65 |    await test
       > 66 |      .click(this.idSelector(cardId).find('#join-group'))
         67 |      .wait(2000)
         68 |    await test
         69 |      .typeText(this.joinGroupModal.find('#group-field'), groupName, { replace: true })
         70 |      .wait(2000)
         71 |    await test

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\members.js:66:8)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 × Check group count (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-40)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-40\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         56 |    await test.expect(identityPanel.state.name).eql(name, 'User name is invalid')
         57 |  }
         58 |  async closeSignupAlert (test) {
         59 |    await test
         60 |      .wait(1000)
       > 61 |      .click(this.signupAlert.find('.q-alert-close').find('.cursor-pointer'))
         62 |      .wait(1000)
         63 |  }
         64 |  async clickToolbar (test, entry) {
         65 |    await test
         66 |      .click(this.appBar.find(entry))

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:61:8)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (D:\Development\kalisio\aktnmap\node_modules\core-js\library\modules\_export.js:36:28)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
         at Authentication.closeSignupAlert (D:\Development\kalisio\aktnmap\test\page-models\layout.js:58:33)
         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\authentication.js:54:16)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 × Remove member from group (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-41)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-41\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         79 |      .wait(5000)
         80 |  }
         81 |  async leaveGroup (test, memberName, groupName) {
         82 |    let cardId = await this.getItemId(test, this.membersGrid, memberName)
         83 |    await test
       > 84 |      .click(this.idSelector(cardId).find('#group-button'))
         85 |      .wait(500)
         86 |    await test
         87 |      .click(Selector('.q-toolbar').find('#leave-group'))
         88 |      .wait(500)
         89 |    await test

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\members.js:84:8)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 × Delete group (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-42)

   1) AssertionError: Invalid collection length: expected 1 to deeply equal 0

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-42\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         104 |    return undefined
         105 |  }
         106 |  async checkCollectionCount (test, collectionSelector, count) {
         107 |    const collection = await collectionSelector.getVue()
         108 |    await test.wait(1000)
       > 109 |    await test.expect(collection.state.items.length).eql(count, 'Invalid collection length')
         110 |  }
         111 |}
         112 |

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:109:54)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 × Clear context (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-43)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-43\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         20 |  async unregisterUsers (test, users) {
         21 |    for (let i in users) {
         22 |      await this.auth.logIn(test, users[i])
         23 |      await this.org.deleteOrganisation(test, users[i].name)
         24 |      await this.account.removeAccount(test, users[i].name)
       > 25 |      await test.click('#login-link')
         26 |      await test.wait(2000)
         27 |    }
         28 |  }
         29 |}
         30 |

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\users.js:25:18)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 Members
 × Users registration (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-44)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-44\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         38 |  }
         39 |  async openSideNav (test) {
         40 |    let isSideNavVisible = await this.isSideNavVisible()
         41 |    if (!isSideNavVisible) {
         42 |      await test
       > 43 |        .click(this.sideNavToggle) // Ensure menu is open
         44 |        .wait(1000)
         45 |    }
         46 |  }
         47 |  async clickIdentity (test) {
         48 |    await this.openSideNav(test)

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:43:10)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 √ Add users to organisation
 × Invite guest to join the organisation (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-46)

   1) AssertionError: Invalid collection length: expected 3 to deeply equal 4

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-46\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         104 |    return undefined
         105 |  }
         106 |  async checkCollectionCount (test, collectionSelector, count) {
         107 |    const collection = await collectionSelector.getVue()
         108 |    await test.wait(1000)
       > 109 |    await test.expect(collection.state.items.length).eql(count, 'Invalid collection length')
         110 |  }
         111 |}
         112 |

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:109:54)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 × tag member (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-47)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-47\Firefox_66.0.0_Windows_10.0.0\errors\1.png

          91 |      .wait(5000)
          92 |  }
          93 |  async tagMember (test, name, tag) {
          94 |    let cardId = await this.getItemId(test, this.membersGrid, name)
          95 |    await test
       >  96 |      .click(this.idSelector(cardId).find('#tag-member'))
          97 |      .wait(1000)
          98 |    await test
          99 |      .typeText(this.tagMemberModal.find('#tags-field'), tag, { replace: true })
         100 |      .wait(2000)
         101 |    await test

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\members.js:96:8)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 √ Change guest role
 × Remove members from organisation (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-49)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-49\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         49 |      .wait(5000)
         50 |  }
         51 |  async removeMember (test, name) {
         52 |    let cardId = await this.getItemId(test, this.membersGrid, name)
         53 |    await test
       > 54 |      .click(this.idSelector(cardId).find('#card-overflow-menu-entry'))
         55 |      .wait(500)
         56 |    await test
         57 |      .click(Selector('.q-popover').find('#remove-member'))
         58 |      .wait(500)
         59 |    await test

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\members.js:54:8)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 × Clean registrated users (screenshots: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-50)

   1) The specified selector does not match any element in the DOM tree.

      Browser: Firefox 66.0.0 / Windows 10.0.0
      Screenshot: D:\Development\kalisio\aktnmap\screenshots\2019-04-13_02-31-53\test-50\Firefox_66.0.0_Windows_10.0.0\errors\1.png

         38 |  }
         39 |  async openSideNav (test) {
         40 |    let isSideNavVisible = await this.isSideNavVisible()
         41 |    if (!isSideNavVisible) {
         42 |      await test
       > 43 |        .click(this.sideNavToggle) // Ensure menu is open
         44 |        .wait(1000)
         45 |    }
         46 |  }
         47 |  async clickIdentity (test) {
         48 |    await this.openSideNav(test)

         at <anonymous> (D:\Development\kalisio\aktnmap\test\page-models\layout.js:43:10)
         at step (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\Development\kalisio\aktnmap\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13)


 Organisations
 √ Registration
 √ Default organisation
(node:18072) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): #<CantObtainInfoForElementSpecifiedBySelectorError>
 √ Forbid additional free org creation
 √ Delete default organisation
 √ Create organisation
(node:18072) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): #<CantObtainInfoForElementSpecifiedBySelectorError>
 √ Forbid account deletion
 √ Delete created organisation
 √ Delete account
(node:18072) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: this.moment.duration(...).format is not a function
```

**Comment by claustres** [comment]
Most tests are now fixed

**Comment by claustres** [comment]
Travis CI does not work however, the testcafe docker image has changed.
